---
name: mclip
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Autoreconf
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Make
        run: make

      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: mclip
          path: src/mclip

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
